language: node_js
node_js:
  - '4.2'
notifications:
  slack:
    secure: IJq5A12JqrFJnBFZqpabG0PJR6DmnRE3v4dqer9kNfZm3NBtzK0doodyVCuLQfMHc82DXHJ4jwWPgAS5UD5mRel8TLMFqlwmK34I+pWdyEY/LHjxRg25SSYt5PlZlycsry/baTsmsP3k6ueS4A/gNiwjZYn8Hs+qguIUvObQKL6Mt0vxpLDIxCLWuaLrXAM0lMgSdZoUR3XgRtyFrEOVKYF9soy0CX9YakD6Ll2y79xRc+v4gIjjJt2AclUgA9HSLjtsrU2pFErQNTN3LbwY+2rQ5WXTx1t06pQzkIgW/NMxGEr97z6XhjuYiGgBNRFubzbfpGu3ilpUCSqhfkXh9i/tBJyAUKqf4USYnuxsvi1+1PNjqGwcWqHqOjqb2dHusNunPhFVuFjripk0RuoMHItojTYRC0F8e6Et8DQjCWHp14WwBTmJWEaDztTqHLXB8aFlf+Y9CbaAXepzsZ7lQhajkeailgYOWUdN8RMWXQeVJVDUjn7B2KdRFd583llfF3sCMxBJZSuqAA0YABW65hZxOgqCJ3bxGxB+5oIfkOSeScG05YLpXO9KOSdC+WvqGHtW32cpAT5ytBdghaSjEM6+NxiX8xicoDLaDOraecw6TrTgEQwcCqOXEe8zcEZR6t18Oj2ZysNwLNboSiMdQYDRxIz7jgjcyEG82aXAiiY=
